# Generated by Django 5.2.1 on 2025-06-21 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_customuser_otp_verified'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='qr_code_image',
            field=models.ImageField(blank=True, null=True, upload_to='qr_codes/'),
        ),
    ]
